name: C
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: cd c/program1 && make build
    - uses: actions/upload-artifact@v3
      with:
        path: c/program1/a.out
