name: C
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  build_lin:
   # strategy: 
    #  matrix: 
   #     target: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: cd c/program1 && make build && which clang && clang --help
    - uses: actions/upload-artifact@v3
      with:
        path: c/program1/a.out
  build_win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      shell: bash
      run: cd c/program1 && make build && ls
    - uses: actions/upload-artifact@v3
      with:
        path: c/program1/a.exe
